---
# according to https://access.redhat.com/security/cve/CVE-2024-6387 - this only affects RHEL9
- name: mitigate CVE-2024-6387 - regression in sshd providing RCE
  hosts: all
  become: True
  vars:
    real_apply_mitigation: "{{ apply_mitigation | default(True) | bool }}"
    ssh_file: /etc/ssh/sshd_config.d/40-cve-2024-6387.conf

  handlers:
    - name: reload sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded

  tasks:
    - name: test that we're running on a supported system
      assert:
        that:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int >= 7

    - name: create mitigation file on RHEL 9+
      ansible.builtin.copy:
        dest: "{{ ssh_file }}"
        content: |
          # resolve cve-2024-6387
          LoginGraceTime 0
        owner: root
        group: root
      notify: reload sshd
      register: rhel9_copy
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 9
        - real_apply_mitigation

    - name: delete mitigation file on RHEL 9+
      ansible.builtin.file:
        path: "{{ ssh_file }}"
        state: absent
      notify: reload sshd
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 9
        - not real_apply_mitigation

    - name: remove mitigation for RHEL 8 or 7
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LoginGraceTime'
        state: absent
      notify: reload sshd
      when:
        - rhel9_copy is skipped
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int < 9

    - name: add rhel9 hosts for test mitigation
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups:
          - test_mitigation
      when:
        - "hostvars[item].ansible_distribution == 'RedHat'"
        - "hostvars[item].ansible_distribution_major_version|int == 9"
        - real_apply_mitigation
      loop: "{{ ansible_play_hosts }}"
      changed_when: false

- name: test mitigation
  hosts: test_mitigation
  become: True
  gather_facts: False

  tasks:
    - name: test mitigation
      command: /usr/sbin/sshd -T
      register: output
      failed_when:
        - output.rc != 0
        - "'logingracetime 0' not in output.stdout_lines"
      changed_when: false
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 9
