---
- name: mitigate CVE-2024-6387 - regression in sshd providing RCE
  hosts: all
  become: True

  handlers:
    - name: reload sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded

  tasks:
    - name: test that we're running on a supported system
      assert:
        that:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int >= 7

    - name: create mitigation file on RHEL 9+
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/40-cve-2024-6387.conf
        content: |
          # resolve cve-2024-6387
          LoginGraceTime 0
        owner: root
        group: root
      notify: reload sshd
      register: rhel9_copy
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int >= 9

    - name: create mitigation for RHEL 8 or 7
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LoginGraceTime'
        line: "LoginGraceTime 0"
      notify: reload sshd
      when: rhel9_copy is skipped

- name: test mitigation
  hosts: all
  become: True
  gather_facts: False

  tasks:
    - name: test mitigation
      command: /usr/sbin/sshd -T
      register: output
      failed_when:
        - output.rc != 0
        - "'logingracetime 0' not in output.stdout_lines"
      changed_when: false
